from __future__ import annotations

from pathlib import Path
from typing import Any

from .workspace import SafeWorkspace, slugify


def _dart_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace("'", "\\'").replace("\n", " ")


def generate_flutter_project(
    app_name: str,
    instruction: str,
    specification: dict[str, Any],
    output_root: str | Path = "generated_apps",
) -> dict[str, Any]:
    package = slugify(app_name)
    workspace = SafeWorkspace(Path(output_root) / package)
    title = _dart_string(app_name)
    goal = _dart_string(instruction)
    screens = specification.get("screens", ["Home", "Projects", "Settings"])
    screen_literals = ", ".join(f"'{_dart_string(str(item))}'" for item in screens)

    files = {
        "pubspec.yaml": f"""name: {package}
description: Generated by NOVAIX AI App Builder
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
""",
        "analysis_options.yaml": "include: package:flutter_lints/flutter.yaml\n",
        "lib/main.dart": f"""import 'package:flutter/material.dart';

void main() => runApp(const NovaixGeneratedApp());

class NovaixGeneratedApp extends StatelessWidget {{
  const NovaixGeneratedApp({{super.key}});

  @override
  Widget build(BuildContext context) {{
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: '{title}',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFF5546E8)),
        useMaterial3: true,
      ),
      home: const HomeScreen(),
    );
  }}
}}

class HomeScreen extends StatefulWidget {{
  const HomeScreen({{super.key}});
  @override
  State<HomeScreen> createState() => _HomeScreenState();
}}

class _HomeScreenState extends State<HomeScreen> {{
  final screens = <String>[{screen_literals}];
  int selected = 0;

  @override
  Widget build(BuildContext context) {{
    return Scaffold(
      appBar: AppBar(title: const Text('{title}')),
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.all(20),
          child: Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [
            Text(screens[selected], style: Theme.of(context).textTheme.headlineMedium),
            const SizedBox(height: 16),
            const Card(child: Padding(
              padding: EdgeInsets.all(18),
              child: Text('{goal}'),
            )),
            const Spacer(),
            FilledButton(
              onPressed: () => ScaffoldMessenger.of(context).showSnackBar(
                const SnackBar(content: Text('NOVAIX generated workflow is ready')),
              ),
              child: const Text('Get Started'),
            ),
          ]),
        ),
      ),
      bottomNavigationBar: NavigationBar(
        selectedIndex: selected,
        onDestinationSelected: (value) => setState(() => selected = value),
        destinations: screens.take(5).map((name) => NavigationDestination(
          icon: const Icon(Icons.apps_rounded), label: name,
        )).toList(),
      ),
    );
  }}
}}
""",
        "test/widget_test.dart": f"""import 'package:flutter_test/flutter_test.dart';
import 'package:{package}/main.dart';

void main() {{
  testWidgets('generated app opens', (tester) async {{
    await tester.pumpWidget(const NovaixGeneratedApp());
    expect(find.text('{title}'), findsOneWidget);
    expect(find.text('Get Started'), findsOneWidget);
  }});
}}
""",
        "README.md": f"""# {app_name}

Generated by NOVAIX AI App Builder.

## Original instruction

{instruction}

## Run

```bash
flutter pub get
flutter analyze
flutter test
flutter run
```
""",
    }
    written = [str(workspace.write_text(path, content)) for path, content in files.items()]
    workspace.write_json("novaix/specification.json", specification)
    workspace.write_json("novaix/build_manifest.json", {
        "generator": "NOVAIX AI App Builder",
        "version": "1.2.0",
        "package": package,
        "files": sorted(files),
    })
    return {"project_path": str(workspace.root), "package": package, "files": written, "file_count": len(files) + 2}
